Description = "Trunk is a basic logging package for Golang."
License = "Apache-2.0"
Name = "Trunk"
Version = 0.1

[Projects]
	[Projects.trunk]
		Destination = ""
		DisableNestedEnvironment = true
		Plugin = "go"
		SimpleName = "trunk"
		Source = "*.go"
		Type = "package"
